---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  require_chef_omnibus: false
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata
  require_chef_for_busser: true

platforms:
  - name: centos6.5
    driver:
        box: chef/centos-6.5

suites:
  - name: default
    provisioner:
        manifest: site.pp
